-- Products Table
CREATE TABLE products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  external_id TEXT,
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  description TEXT,
  price NUMERIC NOT NULL,
  old_price NUMERIC,
  currency TEXT DEFAULT 'UAH',
  images TEXT[],
  attributes JSONB,
  in_stock BOOLEAN DEFAULT TRUE,
  is_bestseller BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Create index on slug for faster lookups
CREATE INDEX idx_products_slug ON products(slug);

-- Create index on external_id for CSV imports
CREATE INDEX idx_products_external_id ON products(external_id);

-- Orders Table
CREATE TABLE orders (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  total_price NUMERIC NOT NULL,
  delivery_info JSONB,
  delivery_method TEXT,
  payment_method TEXT CHECK (payment_method IN ('cash', 'card', 'on_receipt')),
  customer_name TEXT,
  customer_phone TEXT,
  customer_email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Create index on user_id for faster queries
CREATE INDEX idx_orders_user_id ON orders(user_id);

-- Row Level Security for Orders
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Users can view their own orders
CREATE POLICY "Users can view own orders"
  ON orders FOR SELECT
  USING (auth.uid() = user_id);

-- Users can create their own orders
CREATE POLICY "Users can create own orders"
  ON orders FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Admins can view all orders
CREATE POLICY "Admins can view all orders"
  ON orders FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Admins can update orders
CREATE POLICY "Admins can update orders"
  ON orders FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Admins can delete orders
CREATE POLICY "Admins can delete orders"
  ON orders FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Order Items Table
CREATE TABLE order_items (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  quantity INTEGER NOT NULL,
  price_at_purchase NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Create index on order_id for faster queries
CREATE INDEX idx_order_items_order_id ON order_items(order_id);

-- Row Level Security for Order Items
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Users can view their own order items
CREATE POLICY "Users can view own order items"
  ON order_items FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM orders
      WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid()
    )
  );

-- Admins can view all order items
CREATE POLICY "Admins can view all order items"
  ON order_items FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Favorites Table (Auth protected)
CREATE TABLE favorites (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users NOT NULL,
  product_id BIGINT REFERENCES products(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  UNIQUE(user_id, product_id)
);

-- Create index on user_id for faster queries
CREATE INDEX idx_favorites_user_id ON favorites(user_id);

-- Row Level Security for Favorites
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;

-- Users can view their own favorites
CREATE POLICY "Users can view own favorites"
  ON favorites FOR SELECT
  USING (auth.uid() = user_id);

-- Users can add their own favorites
CREATE POLICY "Users can insert own favorites"
  ON favorites FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own favorites
CREATE POLICY "Users can delete own favorites"
  ON favorites FOR DELETE
  USING (auth.uid() = user_id);

-- Row Level Security for Products (publicly readable)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Anyone can view products
CREATE POLICY "Products are publicly readable"
  ON products FOR SELECT
  USING (true);

-- Only service role can modify products (admin operations via backend)
CREATE POLICY "Service role can modify products"
  ON products FOR ALL
  USING (auth.role() = 'service_role');

-- Reviews Table
CREATE TABLE reviews (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users,
  user_name TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
  comment TEXT,
  admin_reply TEXT,
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Create index on product_id for faster queries
CREATE INDEX idx_reviews_product_id ON reviews(product_id);

-- Create index on is_approved for faster filtering
CREATE INDEX idx_reviews_is_approved ON reviews(is_approved);

-- Row Level Security for Reviews
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- Anyone can view approved reviews
CREATE POLICY "Approved reviews are publicly readable"
  ON reviews FOR SELECT
  USING (is_approved = true);

-- Authenticated users can insert reviews
CREATE POLICY "Authenticated users can insert reviews"
  ON reviews FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Only service role can update reviews (admin operations)
CREATE POLICY "Service role can update reviews"
  ON reviews FOR UPDATE
  USING (auth.role() = 'service_role');

-- Only service role can delete reviews (admin operations)
CREATE POLICY "Service role can delete reviews"
  ON reviews FOR DELETE
  USING (auth.role() = 'service_role');

-- Site Settings Table
CREATE TABLE site_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  label TEXT NOT NULL
);

-- Insert default settings
INSERT INTO site_settings (key, value, label) VALUES
  ('phone', '+380 99 378 60 36', 'Номер телефону'),
  ('instagram_url', 'https://www.instagram.com/pava.beauty.ua/', 'Посилання на Instagram'),
  ('address', 'м. Київ', 'Адреса'),
  ('email', 'svitanok@gmail.com', 'Email'),
  ('banner_text', 'Спеціальна пропозиція! Знижки до 30%', 'Текст банера');

-- Row Level Security for Site Settings
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- Only service role can modify site settings (admin operations)
CREATE POLICY "Service role can modify site settings"
  ON site_settings FOR ALL
  USING (auth.role() = 'service_role');

-- Anyone can view site settings
CREATE POLICY "Site settings are publicly readable"
  ON site_settings FOR SELECT
  USING (true);

-- Add TTN column to orders table
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ttn TEXT;
